package ci

// Name defines the CI names.
// NOTE: see https://github.com/npm/ci-detect#cis-detected for full list
type Name = string

const (
	// NoCIDetected indicates no known CI environment has been detected.
	NoCIDetected = Name("")

	Appveyor           = Name("appveyor")
	AWSCodeBuild       = Name("aws-codebuild")
	AzurePipelines     = Name("azure-pipelines")
	Bamboo             = Name("bamboo")
	BitbucketPipelines = Name("bitbucket-pipelines")
	Bitrise            = Name("bitrise")
	Buddy              = Name("buddy")
	Builder            = Name("builder")
	BuildKite          = Name("buildkite")
	CircleCI           = Name("circleci")
	Cirrus             = Name("cirrus")
	Codeship           = Name("codeship")
	Custom             = Name("custom")
	Drone              = Name("drone")
	Dsari              = Name("dsari")
	Gerrit             = Name("gerrit")
	GithubActions      = Name("github-actions")
	Gitlab             = Name("gitlab")
	GoCD               = Name("gocd")
	Heroku             = Name("heroku")
	Hudson             = Name("hudson")
	Jenkins            = Name("jenkins")
	Magnum             = Name("magnum")
	Netlify            = Name("netlify")
	Nevercode          = Name("nevercode")
	Now                = Name("now")
	NowBitbucket       = Name("now-bitbucket")
	NowGitHub          = Name("now-github")
	NowGitLab          = Name("now-gitlab")
	Render             = Name("render")
	Sail               = Name("sail")
	Screwdriver        = Name("screwdriver")
	Semaphore          = Name("semaphore")
	Shippable          = Name("shippable")
	Strider            = Name("strider")
	TaskCluster        = Name("taskcluster")
	Tddium             = Name("tddium")
	TeamCity           = Name("teamcity")
	TravisCI           = Name("travis-ci")
	Vercel             = Name("vercel")
	VercelBitbucket    = Name("vercel-bitbucket")
	VercelGitHub       = Name("vercel-github")
	VercelGitLab       = Name("vercel-gitlab")
	Wercker            = Name("wercker")
	Woodpecker         = Name("woodpecker")
)
